version: '3.0'
services:
  postgres:
    image: postgres:12-alpine
    container_name: node-postgresql
    ports:
      - 15432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - ./.docker.env
volumes:
  db_data: {}